import {
  Users,
  Video,
  Newspaper,
  Trophy,
  Code,
  MusicNotes,
  ShoppingCart,
  Briefcase,
  Bank,
  AirplaneTilt,
  GraduationCap,
  Robot,
  GameController,
  ForkKnife,
  Heartbeat,
  ChatCircleDots,
  Globe,
  Bookmarks,
  CloudArrowUp,
  Chats,
  Storefront,
  Suitcase,
  FilmSlate,
  MapPin,
} from '@phosphor-icons/react';

// ─────────────────────────────────────────────
// Auto Tab Grouper — Pre-configured Templates
// ─────────────────────────────────────────────
// Design principles:
//  1. Universal templates first — instantly recognizable to anyone.
//  2. Regional variants grouped by geography — users self-select.
//  3. Every template should make a user think "yes, I open those tabs."
//  4. Domains sourced from Similarweb / Semrush global top-500 + regional lists.

// ─────────────────────────────────────────────
// Region Hierarchy
// ─────────────────────────────────────────────

export const REGION_TREE = [
  { id: 'global',   label: '🌐', title: 'All Regions', children: [] },
  {
    id: 'na', label: '🌎', title: 'North America',
    children: [
      { id: 'na.us',     label: '🇺🇸', title: 'United States' },
      { id: 'na.ca',     label: '🇨🇦', title: 'Canada' },
    ],
  },
  {
    id: 'europe', label: '🇪🇺', title: 'Europe',
    children: [
      { id: 'europe.uk',     label: '🇬🇧', title: 'United Kingdom' },
      { id: 'europe.de',     label: '🇩🇪', title: 'Germany' },
      { id: 'europe.fr',     label: '🇫🇷', title: 'France' },
    ],
  },
  {
    id: 'eastasia', label: '🌏', title: 'East Asia',
    children: [
      { id: 'eastasia.china', label: '🇨🇳', title: 'China' },
      { id: 'eastasia.korea', label: '🇰🇷', title: 'South Korea' },
      { id: 'eastasia.japan', label: '🇯🇵', title: 'Japan' },
    ],
  },
  {
    id: 'southasia', label: '🌏', title: 'South Asia',
    children: [
      { id: 'southasia.india', label: '🇮🇳', title: 'India' },
    ],
  },
  { id: 'latam',  label: '🌎', title: 'Latin America', children: [] },
  { id: 'mena',   label: '🌍', title: 'Middle East & North Africa',
    children: [
      { id: 'mena.gulf', label: '🌍', title: 'Gulf States' },
    ],
  },
];

// Flat lookup helper: any id → { label, title }
const _regionFlat = (() => {
  const m = {};
  function walk(nodes) {
    for (const n of nodes) {
      m[n.id] = { label: n.label, title: n.title };
      if (n.children?.length) walk(n.children);
    }
  }
  walk(REGION_TREE);
  return m;
})();

export function getRegionMeta(regionId) {
  return _regionFlat[regionId] ?? { label: '🌐', title: regionId };
}

// Coverage map — which categories each region has
  export const REGION_COVERAGE_MAP = {
    global: [
      'social', 'video', 'music', 'news', 'shopping', 'work',
      'developer', 'ai', 'messaging', 'gaming', 'sports',
      'finance', 'education', 'travel', 'food', 'health',
      'cloud', 'jobs', 'reading', 'forums', 'google',
    ],
    'na.ca':           ['finance', 'google', 'health', 'jobs', 'news', 'shopping', 'sports', 'work'],
    'europe.uk':       ['finance', 'food', 'google', 'jobs', 'news', 'shopping', 'sports', 'travel', 'video', 'work'],
    'europe.de':       ['finance', 'food', 'google', 'health', 'jobs', 'news', 'shopping', 'sports', 'travel'],
    'europe.fr':       ['finance', 'food', 'google', 'jobs', 'news', 'shopping', 'sports', 'travel'],
    'eastasia.china':  ['ai', 'cloud', 'finance', 'gaming', 'jobs', 'messaging', 'music', 'news', 'shopping', 'social', 'video', 'work'],
    'eastasia.korea':  ['finance', 'forums', 'gaming', 'google', 'jobs', 'messaging', 'news', 'reading', 'shopping', 'social'],
    'eastasia.japan':  ['finance', 'food', 'forums', 'gaming', 'google', 'messaging', 'news', 'reading', 'shopping', 'social', 'travel'],
    'southasia.india': ['education', 'finance', 'food', 'google', 'jobs', 'news', 'shopping', 'travel', 'video'],
    'latam':           ['education', 'finance', 'google', 'jobs', 'news', 'shopping', 'travel'],
    'mena.gulf':       ['finance', 'food', 'google', 'health', 'news', 'shopping', 'travel', 'work'],
  };


export const PRESET_TEMPLATES = [

  // ───── UNIVERSAL ─────

  {
    id: "template-social",
    category: "social",
    region: "global",
    groupName: "Social",
    icon: Users,
    groupColor: "pink",
    strict: true,
    merge: false,
    patterns: [
      { value: "facebook.com", type: "simple", isRegex: false },
      { value: "instagram.com", type: "simple", isRegex: false },
      { value: "x.com", type: "simple", isRegex: false },
      { value: "twitter.com", type: "simple", isRegex: false },
      { value: "linkedin.com", type: "simple", isRegex: false },
      { value: "tiktok.com", type: "simple", isRegex: false },
      { value: "reddit.com", type: "simple", isRegex: false },
      { value: "threads.net", type: "simple", isRegex: false },
      { value: "pinterest.com", type: "simple", isRegex: false },
      { value: "snapchat.com", type: "simple", isRegex: false },
      { value: "tumblr.com", type: "simple", isRegex: false },
      { value: "mastodon.social", type: "simple", isRegex: false },
      { value: "bluesky.social", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-video",
    category: "video",
    region: "global",
    groupName: "Video",
    icon: Video,
    groupColor: "red",
    strict: true,
    merge: false,
    patterns: [
      { value: "youtube.com", type: "simple", isRegex: false },
      { value: "netflix.com", type: "simple", isRegex: false },
      { value: "twitch.tv", type: "simple", isRegex: false },
      { value: "hulu.com", type: "simple", isRegex: false },
      { value: "disneyplus.com", type: "simple", isRegex: false },
      { value: "primevideo.com", type: "simple", isRegex: false },
      { value: "crunchyroll.com", type: "simple", isRegex: false },
      { value: "vimeo.com", type: "simple", isRegex: false },
      { value: "dailymotion.com", type: "simple", isRegex: false },
      { value: "max.com", type: "simple", isRegex: false },
      { value: "paramountplus.com", type: "simple", isRegex: false },
      { value: "ted.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-work",
    category: "work",
    region: "global",
    groupName: "Work",
    icon: Briefcase,
    groupColor: "blue",
    strict: true,
    merge: true,
    patterns: [
      { value: "docs.google.com", type: "simple", isRegex: false },
      { value: "sheets.google.com", type: "simple", isRegex: false },
      { value: "slides.google.com", type: "simple", isRegex: false },
      { value: "notion.so", type: "simple", isRegex: false },
      { value: "slack.com", type: "simple", isRegex: false },
      { value: "figma.com", type: "simple", isRegex: false },
      { value: "trello.com", type: "simple", isRegex: false },
      { value: "asana.com", type: "simple", isRegex: false },
      { value: "atlassian.net", type: "simple", isRegex: false },
      { value: "jira.com", type: "simple", isRegex: false },
      { value: "monday.com", type: "simple", isRegex: false },
      { value: "miro.com", type: "simple", isRegex: false },
      { value: "zoom.us", type: "simple", isRegex: false },
      { value: "microsoft365.com", type: "simple", isRegex: false },
      { value: "clickup.com", type: "simple", isRegex: false },
      { value: "airtable.com", type: "simple", isRegex: false },
      { value: "canva.com", type: "simple", isRegex: false },
      { value: "basecamp.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-messaging",
    category: "messaging",
    region: "global",
    groupName: "Messaging",
    icon: Chats,
    groupColor: "green",
    strict: true,
    merge: false,
    patterns: [
      { value: "web.whatsapp.com", type: "simple", isRegex: false },
      { value: "discord.com", type: "simple", isRegex: false },
      { value: "telegram.org", type: "simple", isRegex: false },
      { value: "messenger.com", type: "simple", isRegex: false },
      { value: "teams.microsoft.com", type: "simple", isRegex: false },
      { value: "signal.org", type: "simple", isRegex: false },
      { value: "skype.com", type: "simple", isRegex: false },
      { value: "viber.com", type: "simple", isRegex: false },
      { value: "line.me", type: "simple", isRegex: false },
      { value: "wechat.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-shopping",
    category: "shopping",
    region: "global",
    groupName: "Shopping",
    icon: ShoppingCart,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "amazon.com", type: "simple", isRegex: false },
      { value: "ebay.com", type: "simple", isRegex: false },
      { value: "etsy.com", type: "simple", isRegex: false },
      { value: "walmart.com", type: "simple", isRegex: false },
      { value: "target.com", type: "simple", isRegex: false },
      { value: "bestbuy.com", type: "simple", isRegex: false },
      { value: "temu.com", type: "simple", isRegex: false },
      { value: "aliexpress.com", type: "simple", isRegex: false },
      { value: "alibaba.com", type: "simple", isRegex: false },
      { value: "shein.com", type: "simple", isRegex: false },
      { value: "ikea.com", type: "simple", isRegex: false },
      { value: "zara.com", type: "simple", isRegex: false },
      { value: "shopify.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-news",
    category: "news",
    region: "global",
    groupName: "News",
    icon: Newspaper,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "news.google.com", type: "simple", isRegex: false },
      { value: "nytimes.com", type: "simple", isRegex: false },
      { value: "bbc.com", type: "simple", isRegex: false },
      { value: "cnn.com", type: "simple", isRegex: false },
      { value: "reuters.com", type: "simple", isRegex: false },
      { value: "apnews.com", type: "simple", isRegex: false },
      { value: "theguardian.com", type: "simple", isRegex: false },
      { value: "aljazeera.com", type: "simple", isRegex: false },
      { value: "bloomberg.com", type: "simple", isRegex: false },
      { value: "wsj.com", type: "simple", isRegex: false },
      { value: "forbes.com", type: "simple", isRegex: false },
      { value: "ft.com", type: "simple", isRegex: false },
      { value: "economist.com", type: "simple", isRegex: false },
      { value: "time.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-ai",
    category: "ai",
    region: "global",
    groupName: "AI",
    icon: Robot,
    groupColor: "cyan",
    strict: true,
    merge: false,
    patterns: [
      { value: "chatgpt.com", type: "simple", isRegex: false },
      { value: "claude.ai", type: "simple", isRegex: false },
      { value: "gemini.google.com", type: "simple", isRegex: false },
      { value: "perplexity.ai", type: "simple", isRegex: false },
      { value: "poe.com", type: "simple", isRegex: false },
      { value: "huggingface.co", type: "simple", isRegex: false },
      { value: "mistral.ai", type: "simple", isRegex: false },
      { value: "midjourney.com", type: "simple", isRegex: false },
      { value: "deepseek.com", type: "simple", isRegex: false },
      { value: "groq.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-dev",
    category: "developer",
    region: "global",
    groupName: "Developer",
    icon: Code,
    groupColor: "purple",
    strict: true,
    merge: false,
    patterns: [
      { value: "github.com", type: "simple", isRegex: false },
      { value: "stackoverflow.com", type: "simple", isRegex: false },
      { value: "gitlab.com", type: "simple", isRegex: false },
      { value: "dev.to", type: "simple", isRegex: false },
      { value: "npmjs.com", type: "simple", isRegex: false },
      { value: "vercel.com", type: "simple", isRegex: false },
      { value: "bitbucket.org", type: "simple", isRegex: false },
      { value: "docker.com", type: "simple", isRegex: false },
      { value: "netlify.com", type: "simple", isRegex: false },
      { value: "mdn.mozilla.org", type: "simple", isRegex: false },
      { value: "postman.com", type: "simple", isRegex: false },
      { value: "jetbrains.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-finance",
    category: "finance",
    region: "global",
    groupName: "Finance",
    icon: Bank,
    groupColor: "green",
    strict: true,
    merge: false,
    patterns: [
      { value: "chase.com", type: "simple", isRegex: false },
      { value: "bankofamerica.com", type: "simple", isRegex: false },
      { value: "wellsfargo.com", type: "simple", isRegex: false },
      { value: "paypal.com", type: "simple", isRegex: false },
      { value: "venmo.com", type: "simple", isRegex: false },
      { value: "mint.intuit.com", type: "simple", isRegex: false },
      { value: "revolut.com", type: "simple", isRegex: false },
      { value: "wise.com", type: "simple", isRegex: false },
      { value: "stripe.com", type: "simple", isRegex: false },
      { value: "coinbase.com", type: "simple", isRegex: false },
      { value: "binance.com", type: "simple", isRegex: false },
      { value: "hsbc.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-music",
    category: "music",
    region: "global",
    groupName: "Music",
    icon: MusicNotes,
    groupColor: "green",
    strict: true,
    merge: false,
    patterns: [
      { value: "spotify.com", type: "simple", isRegex: false },
      { value: "music.apple.com", type: "simple", isRegex: false },
      { value: "soundcloud.com", type: "simple", isRegex: false },
      { value: "music.youtube.com", type: "simple", isRegex: false },
      { value: "tidal.com", type: "simple", isRegex: false },
      { value: "pandora.com", type: "simple", isRegex: false },
      { value: "deezer.com", type: "simple", isRegex: false },
      { value: "bandcamp.com", type: "simple", isRegex: false },
      { value: "last.fm", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-gaming",
    category: "gaming",
    region: "global",
    groupName: "Gaming",
    icon: GameController,
    groupColor: "purple",
    strict: true,
    merge: false,
    patterns: [
      { value: "store.steampowered.com", type: "simple", isRegex: false },
      { value: "epicgames.com", type: "simple", isRegex: false },
      { value: "ign.com", type: "simple", isRegex: false },
      { value: "twitch.tv", type: "simple", isRegex: false },
      { value: "roblox.com", type: "simple", isRegex: false },
      { value: "ea.com", type: "simple", isRegex: false },
      { value: "playstation.com", type: "simple", isRegex: false },
      { value: "xbox.com", type: "simple", isRegex: false },
      { value: "nintendo.com", type: "simple", isRegex: false },
      { value: "gamespot.com", type: "simple", isRegex: false },
      { value: "discord.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-education",
    category: "education",
    region: "global",
    groupName: "Education",
    icon: GraduationCap,
    groupColor: "yellow",
    strict: true,
    merge: false,
    patterns: [
      { value: "canvas.instructure.com", type: "simple", isRegex: false },
      { value: "blackboard.com", type: "simple", isRegex: false },
      { value: "coursera.org", type: "simple", isRegex: false },
      { value: "khanacademy.org", type: "simple", isRegex: false },
      { value: "quizlet.com", type: "simple", isRegex: false },
      { value: "edx.org", type: "simple", isRegex: false },
      { value: "udemy.com", type: "simple", isRegex: false },
      { value: "duolingo.com", type: "simple", isRegex: false },
      { value: "skillshare.com", type: "simple", isRegex: false },
      { value: "masterclass.com", type: "simple", isRegex: false },
      { value: "chegg.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-sports",
    category: "sports",
    region: "global",
    groupName: "Sports",
    icon: Trophy,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "espn.com", type: "simple", isRegex: false },
      { value: "theathletic.com", type: "simple", isRegex: false },
      { value: "cbssports.com", type: "simple", isRegex: false },
      { value: "nba.com", type: "simple", isRegex: false },
      { value: "nfl.com", type: "simple", isRegex: false },
      { value: "mlb.com", type: "simple", isRegex: false },
      { value: "fifa.com", type: "simple", isRegex: false },
      { value: "olympics.com", type: "simple", isRegex: false },
      { value: "skysports.com", type: "simple", isRegex: false },
      { value: "bleacherreport.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-travel",
    category: "travel",
    region: "global",
    groupName: "Travel",
    icon: AirplaneTilt,
    groupColor: "cyan",
    strict: false,
    merge: false,
    patterns: [
      { value: "google.com/travel", type: "simple", isRegex: false },
      { value: "airbnb.com", type: "simple", isRegex: false },
      { value: "booking.com", type: "simple", isRegex: false },
      { value: "expedia.com", type: "simple", isRegex: false },
      { value: "kayak.com", type: "simple", isRegex: false },
      { value: "tripadvisor.com", type: "simple", isRegex: false },
      { value: "skyscanner.net", type: "simple", isRegex: false },
      { value: "hotels.com", type: "simple", isRegex: false },
      { value: "trip.com", type: "simple", isRegex: false },
      { value: "marriott.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-jobs",
    category: "jobs",
    region: "global",
    groupName: "Jobs",
    icon: Suitcase,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "linkedin.com/jobs", type: "simple", isRegex: false },
      { value: "indeed.com", type: "simple", isRegex: false },
      { value: "glassdoor.com", type: "simple", isRegex: false },
      { value: "ziprecruiter.com", type: "simple", isRegex: false },
      { value: "wellfound.com", type: "simple", isRegex: false },
      { value: "monster.com", type: "simple", isRegex: false },
      { value: "careerbuilder.com", type: "simple", isRegex: false },
      { value: "upwork.com", type: "simple", isRegex: false },
      { value: "fiverr.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-health",
    category: "health",
    region: "global",
    groupName: "Health",
    icon: Heartbeat,
    groupColor: "red",
    strict: false,
    merge: false,
    patterns: [
      { value: "webmd.com", type: "simple", isRegex: false },
      { value: "mayoclinic.org", type: "simple", isRegex: false },
      { value: "healthline.com", type: "simple", isRegex: false },
      { value: "nih.gov", type: "simple", isRegex: false },
      { value: "myfitnesspal.com", type: "simple", isRegex: false },
      { value: "who.int", type: "simple", isRegex: false },
      { value: "strava.com", type: "simple", isRegex: false },
      { value: "headspace.com", type: "simple", isRegex: false },
      { value: "fitbit.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-reading",
    category: "reading",
    region: "global",
    groupName: "Reading",
    icon: Bookmarks,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "medium.com", type: "simple", isRegex: false },
      { value: "substack.com", type: "simple", isRegex: false },
      { value: "wikipedia.org", type: "simple", isRegex: false },
      { value: "goodreads.com", type: "simple", isRegex: false },
      { value: "pocket.com", type: "simple", isRegex: false },
      { value: "wattpad.com", type: "simple", isRegex: false },
      { value: "scribd.com", type: "simple", isRegex: false },
      { value: "archive.org", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-cloud",
    category: "cloud",
    region: "global",
    groupName: "Cloud",
    icon: CloudArrowUp,
    groupColor: "blue",
    strict: true,
    merge: false,
    patterns: [
      { value: "drive.google.com", type: "simple", isRegex: false },
      { value: "dropbox.com", type: "simple", isRegex: false },
      { value: "onedrive.live.com", type: "simple", isRegex: false },
      { value: "icloud.com", type: "simple", isRegex: false },
      { value: "box.com", type: "simple", isRegex: false },
      { value: "mega.nz", type: "simple", isRegex: false },
      { value: "pcloud.com", type: "simple", isRegex: false },
      { value: "adobe.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-food",
    category: "food",
    region: "global",
    groupName: "Food",
    icon: ForkKnife,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "doordash.com", type: "simple", isRegex: false },
      { value: "ubereats.com", type: "simple", isRegex: false },
      { value: "grubhub.com", type: "simple", isRegex: false },
      { value: "yelp.com", type: "simple", isRegex: false },
      { value: "allrecipes.com", type: "simple", isRegex: false },
      { value: "deliveroo.com", type: "simple", isRegex: false },
      { value: "just-eat.com", type: "simple", isRegex: false },
      { value: "hellofresh.com", type: "simple", isRegex: false },
      { value: "tasty.co", type: "simple", isRegex: false },
      { value: "michelin.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-forums",
    category: "forums",
    region: "global",
    groupName: "Forums",
    icon: ChatCircleDots,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "reddit.com", type: "simple", isRegex: false },
      { value: "quora.com", type: "simple", isRegex: false },
      { value: "stackexchange.com", type: "simple", isRegex: false },
      { value: "news.ycombinator.com", type: "simple", isRegex: false },
      { value: "4chan.org", type: "simple", isRegex: false },
      { value: "macrumors.com", type: "simple", isRegex: false },
      { value: "avforums.com", type: "simple", isRegex: false },
    ],
  },

  // ───── UNIVERSAL: GOOGLE ─────

  {
    id: "template-google",
    category: "google",
    region: "global",
    groupName: "Google",
    icon: Globe,
    groupColor: "blue",
    strict: true,
    merge: false,
    patterns: [
      { value: "google.com", type: "simple", isRegex: false },
      { value: "mail.google.com", type: "simple", isRegex: false },
      { value: "drive.google.com", type: "simple", isRegex: false },
      { value: "docs.google.com", type: "simple", isRegex: false },
      { value: "sheets.google.com", type: "simple", isRegex: false },
      { value: "slides.google.com", type: "simple", isRegex: false },
      { value: "maps.google.com", type: "simple", isRegex: false },
      { value: "calendar.google.com", type: "simple", isRegex: false },
      { value: "photos.google.com", type: "simple", isRegex: false },
      { value: "meet.google.com", type: "simple", isRegex: false },
      { value: "translate.google.com", type: "simple", isRegex: false },
      { value: "play.google.com", type: "simple", isRegex: false },
      { value: "classroom.google.com", type: "simple", isRegex: false },
      { value: "earth.google.com", type: "simple", isRegex: false },
      { value: "shopping.google.com", type: "simple", isRegex: false },
      { value: "keep.google.com", type: "simple", isRegex: false },
      { value: "one.google.com", type: "simple", isRegex: false },
      { value: "voice.google.com", type: "simple", isRegex: false },
      { value: "contacts.google.com", type: "simple", isRegex: false },
      { value: "accounts.google.com", type: "simple", isRegex: false },
    ],
  },

  // ───── REGIONAL: NA.CA ─────

  {
    id: "template-na-ca-finance",
    category: "finance",
    region: "na.ca",
    groupName: "🇨🇦 Finance",
    icon: Bank,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "td.com", type: "simple", isRegex: false },
      { value: "rbc.com", type: "simple", isRegex: false },
      { value: "scotiabank.com", type: "simple", isRegex: false },
      { value: "bmo.com", type: "simple", isRegex: false },
      { value: "cibc.com", type: "simple", isRegex: false },
      { value: "interac.ca", type: "simple", isRegex: false },
      { value: "wealthsimple.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-na-ca-health",
    category: "health",
    region: "na.ca",
    groupName: "🇨🇦 Health",
    icon: Heartbeat,
    groupColor: "red",
    strict: false,
    merge: false,
    patterns: [
      { value: "alberta.ca", type: "simple", isRegex: false },
      { value: "ontario.ca", type: "simple", isRegex: false },
      { value: "janeapp.com", type: "simple", isRegex: false },
      { value: "lifelabs.com", type: "simple", isRegex: false },
      { value: "salutbonjour.ca", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-na-ca-jobs",
    category: "jobs",
    region: "na.ca",
    groupName: "🇨🇦 Jobs",
    icon: Suitcase,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "indeed.ca", type: "simple", isRegex: false },
      { value: "randstad.ca", type: "simple", isRegex: false },
      { value: "jobbank.gc.ca", type: "simple", isRegex: false },
      { value: "workopolis.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-na-ca-news",
    category: "news",
    region: "na.ca",
    groupName: "🇨🇦 News",
    icon: Newspaper,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "cbc.ca", type: "simple", isRegex: false },
      { value: "theglobeandmail.com", type: "simple", isRegex: false },
      { value: "ctvnews.ca", type: "simple", isRegex: false },
      { value: "torontostar.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-na-ca-shopping",
    category: "shopping",
    region: "na.ca",
    groupName: "🇨🇦 Shopping",
    icon: ShoppingCart,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "amazon.ca", type: "simple", isRegex: false },
      { value: "walmart.ca", type: "simple", isRegex: false },
      { value: "kijiji.ca", type: "simple", isRegex: false },
      { value: "canadiantire.ca", type: "simple", isRegex: false },
      { value: "bestbuy.ca", type: "simple", isRegex: false },
      { value: "costco.ca", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-na-ca-sports",
    category: "sports",
    region: "na.ca",
    groupName: "🇨🇦 Sports",
    icon: Trophy,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "nhl.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-na-ca-work",
    category: "work",
    region: "na.ca",
    groupName: "🇨🇦 Work",
    icon: Briefcase,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "canada.ca", type: "simple", isRegex: false },
      { value: "cra-arc.gc.ca", type: "simple", isRegex: false },
      { value: "tpsgc-pwgsc.gc.ca", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-na-ca-google",
    category: "google",
    region: "na.ca",
    groupName: "🇨🇦 Google",
    icon: Globe,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "google.ca", type: "simple", isRegex: false },
    ],
  },

  // ───── REGIONAL: EUROPE.UK ─────

  {
    id: "template-europe-uk-finance",
    category: "finance",
    region: "europe.uk",
    groupName: "🇬🇧 Finance",
    icon: Bank,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "barclays.co.uk", type: "simple", isRegex: false },
      { value: "hsbc.co.uk", type: "simple", isRegex: false },
      { value: "natwest.com", type: "simple", isRegex: false },
      { value: "lloydsbank.com", type: "simple", isRegex: false },
      { value: "monzo.com", type: "simple", isRegex: false },
      { value: "revolut.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-uk-food",
    category: "food",
    region: "europe.uk",
    groupName: "🇬🇧 Food",
    icon: ForkKnife,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "just-eat.co.uk", type: "simple", isRegex: false },
      { value: "deliveroo.co.uk", type: "simple", isRegex: false },
      { value: "bbcgoodfood.com", type: "simple", isRegex: false },
      { value: "ocado.com", type: "simple", isRegex: false },
      { value: "waitrose.com", type: "simple", isRegex: false },
      { value: "morrisons.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-uk-jobs",
    category: "jobs",
    region: "europe.uk",
    groupName: "🇬🇧 Jobs",
    icon: Suitcase,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "reed.co.uk", type: "simple", isRegex: false },
      { value: "totaljobs.com", type: "simple", isRegex: false },
      { value: "cv-library.co.uk", type: "simple", isRegex: false },
      { value: "adzuna.co.uk", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-uk-news",
    category: "news",
    region: "europe.uk",
    groupName: "🇬🇧 News",
    icon: Newspaper,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "bbc.co.uk", type: "simple", isRegex: false },
      { value: "theguardian.com", type: "simple", isRegex: false },
      { value: "dailymail.co.uk", type: "simple", isRegex: false },
      { value: "telegraph.co.uk", type: "simple", isRegex: false },
      { value: "thesun.co.uk", type: "simple", isRegex: false },
      { value: "mirror.co.uk", type: "simple", isRegex: false },
      { value: "express.co.uk", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-uk-shopping",
    category: "shopping",
    region: "europe.uk",
    groupName: "🇬🇧 Shopping",
    icon: ShoppingCart,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "amazon.co.uk", type: "simple", isRegex: false },
      { value: "ebay.co.uk", type: "simple", isRegex: false },
      { value: "argos.co.uk", type: "simple", isRegex: false },
      { value: "asda.com", type: "simple", isRegex: false },
      { value: "tesco.com", type: "simple", isRegex: false },
      { value: "marksandspencer.com", type: "simple", isRegex: false },
      { value: "next.co.uk", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-uk-sports",
    category: "sports",
    region: "europe.uk",
    groupName: "🇬🇧 Sports",
    icon: Trophy,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "skysports.com", type: "simple", isRegex: false },
      { value: "bbc.co.uk/sport", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-uk-travel",
    category: "travel",
    region: "europe.uk",
    groupName: "🇬🇧 Travel",
    icon: AirplaneTilt,
    groupColor: "cyan",
    strict: false,
    merge: false,
    patterns: [
      { value: "trainline.com", type: "simple", isRegex: false },
      { value: "booking.com", type: "simple", isRegex: false },
      { value: "tui.co.uk", type: "simple", isRegex: false },
      { value: "britishairways.com", type: "simple", isRegex: false },
      { value: "easyjet.com", type: "simple", isRegex: false },
      { value: "autotrader.co.uk", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-uk-video",
    category: "video",
    region: "europe.uk",
    groupName: "🇬🇧 Video",
    icon: Video,
    groupColor: "red",
    strict: false,
    merge: false,
    patterns: [
      { value: "itv.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-uk-work",
    category: "work",
    region: "europe.uk",
    groupName: "🇬🇧 Work",
    icon: Briefcase,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "gov.uk", type: "simple", isRegex: false },
      { value: "service.gov.uk", type: "simple", isRegex: false },
      { value: "royalmail.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-uk-google",
    category: "google",
    region: "europe.uk",
    groupName: "🇬🇧 Google",
    icon: Globe,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "google.co.uk", type: "simple", isRegex: false },
    ],
  },

  // ───── REGIONAL: EUROPE.DE ─────

  {
    id: "template-europe-de-finance",
    category: "finance",
    region: "europe.de",
    groupName: "🇩🇪 Finance",
    icon: Bank,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "paypal.com", type: "simple", isRegex: false },
      { value: "sparkasse.de", type: "simple", isRegex: false },
      { value: "finanzen.net", type: "simple", isRegex: false },
      { value: "klarna.com", type: "simple", isRegex: false },
      { value: "ing.de", type: "simple", isRegex: false },
      { value: "comdirect.de", type: "simple", isRegex: false },
      { value: "elster.de", type: "simple", isRegex: false },
      { value: "onvista.de", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-de-food",
    category: "food",
    region: "europe.de",
    groupName: "🇩🇪 Food",
    icon: ForkKnife,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "lieferando.de", type: "simple", isRegex: false },
      { value: "hellofresh.de", type: "simple", isRegex: false },
      { value: "rewe.de", type: "simple", isRegex: false },
      { value: "edeka.de", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-de-health",
    category: "health",
    region: "europe.de",
    groupName: "🇩🇪 Health",
    icon: Heartbeat,
    groupColor: "red",
    strict: false,
    merge: false,
    patterns: [
      { value: "shop-apotheke.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-de-jobs",
    category: "jobs",
    region: "europe.de",
    groupName: "🇩🇪 Jobs",
    icon: Suitcase,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "stepstone.de", type: "simple", isRegex: false },
      { value: "xing.com", type: "simple", isRegex: false },
      { value: "indeed.de", type: "simple", isRegex: false },
      { value: "monster.de", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-de-news",
    category: "news",
    region: "europe.de",
    groupName: "🇩🇪 News",
    icon: Newspaper,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "bild.de", type: "simple", isRegex: false },
      { value: "spiegel.de", type: "simple", isRegex: false },
      { value: "tagesschau.de", type: "simple", isRegex: false },
      { value: "welt.de", type: "simple", isRegex: false },
      { value: "zeit.de", type: "simple", isRegex: false },
      { value: "focus.de", type: "simple", isRegex: false },
      { value: "faz.net", type: "simple", isRegex: false },
      { value: "n-tv.de", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-de-shopping",
    category: "shopping",
    region: "europe.de",
    groupName: "🇩🇪 Shopping",
    icon: ShoppingCart,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "amazon.de", type: "simple", isRegex: false },
      { value: "ebay.de", type: "simple", isRegex: false },
      { value: "otto.de", type: "simple", isRegex: false },
      { value: "zalando.de", type: "simple", isRegex: false },
      { value: "kleinanzeigen.de", type: "simple", isRegex: false },
      { value: "idealo.de", type: "simple", isRegex: false },
      { value: "mediamarkt.de", type: "simple", isRegex: false },
      { value: "lidl.de", type: "simple", isRegex: false },
      { value: "shop-apotheke.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-de-sports",
    category: "sports",
    region: "europe.de",
    groupName: "🇩🇪 Sports",
    icon: Trophy,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "kicker.de", type: "simple", isRegex: false },
      { value: "sport1.de", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-de-travel",
    category: "travel",
    region: "europe.de",
    groupName: "🇩🇪 Travel",
    icon: AirplaneTilt,
    groupColor: "cyan",
    strict: false,
    merge: false,
    patterns: [
      { value: "bahn.de", type: "simple", isRegex: false },
      { value: "check24.de", type: "simple", isRegex: false },
      { value: "booking.com", type: "simple", isRegex: false },
      { value: "lufthansa.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-de-google",
    category: "google",
    region: "europe.de",
    groupName: "🇩🇪 Google",
    icon: Globe,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "google.de", type: "simple", isRegex: false },
    ],
  },

  // ───── REGIONAL: EUROPE.FR ─────

  {
    id: "template-europe-fr-finance",
    category: "finance",
    region: "europe.fr",
    groupName: "🇫🇷 Finance",
    icon: Bank,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "credit-agricole.fr", type: "simple", isRegex: false },
      { value: "boursorama.com", type: "simple", isRegex: false },
      { value: "labanquepostale.fr", type: "simple", isRegex: false },
      { value: "creditmutuel.fr", type: "simple", isRegex: false },
      { value: "lcl.fr", type: "simple", isRegex: false },
      { value: "bnpparibas.fr", type: "simple", isRegex: false },
      { value: "cic.fr", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-fr-food",
    category: "food",
    region: "europe.fr",
    groupName: "🇫🇷 Food",
    icon: ForkKnife,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "ubereats.com", type: "simple", isRegex: false },
      { value: "deliveroo.fr", type: "simple", isRegex: false },
      { value: "marmiton.org", type: "simple", isRegex: false },
      { value: "carrefour.fr", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-fr-jobs",
    category: "jobs",
    region: "europe.fr",
    groupName: "🇫🇷 Jobs",
    icon: Suitcase,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "pole-emploi.fr", type: "simple", isRegex: false },
      { value: "welcometothejungle.com", type: "simple", isRegex: false },
      { value: "hellowork.com", type: "simple", isRegex: false },
      { value: "cadremploi.fr", type: "simple", isRegex: false },
      { value: "malt.fr", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-fr-news",
    category: "news",
    region: "europe.fr",
    groupName: "🇫🇷 News",
    icon: Newspaper,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "lemonde.fr", type: "simple", isRegex: false },
      { value: "lefigaro.fr", type: "simple", isRegex: false },
      { value: "actu.fr", type: "simple", isRegex: false },
      { value: "20minutes.fr", type: "simple", isRegex: false },
      { value: "bfmtv.com", type: "simple", isRegex: false },
      { value: "francetvinfo.fr", type: "simple", isRegex: false },
      { value: "leparisien.fr", type: "simple", isRegex: false },
      { value: "liberation.fr", type: "simple", isRegex: false },
      { value: "franceinfo.fr", type: "simple", isRegex: false },
      { value: "ouest-france.fr", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-fr-shopping",
    category: "shopping",
    region: "europe.fr",
    groupName: "🇫🇷 Shopping",
    icon: ShoppingCart,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "amazon.fr", type: "simple", isRegex: false },
      { value: "leboncoin.fr", type: "simple", isRegex: false },
      { value: "cdiscount.com", type: "simple", isRegex: false },
      { value: "veepee.fr", type: "simple", isRegex: false },
      { value: "fnac.com", type: "simple", isRegex: false },
      { value: "darty.com", type: "simple", isRegex: false },
      { value: "laredoute.fr", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-fr-sports",
    category: "sports",
    region: "europe.fr",
    groupName: "🇫🇷 Sports",
    icon: Trophy,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "lequipe.fr", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-fr-travel",
    category: "travel",
    region: "europe.fr",
    groupName: "🇫🇷 Travel",
    icon: AirplaneTilt,
    groupColor: "cyan",
    strict: false,
    merge: false,
    patterns: [
      { value: "sncf-connect.com", type: "simple", isRegex: false },
      { value: "booking.com", type: "simple", isRegex: false },
      { value: "airbnb.fr", type: "simple", isRegex: false },
      { value: "airfrance.fr", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-europe-fr-google",
    category: "google",
    region: "europe.fr",
    groupName: "🇫🇷 Google",
    icon: Globe,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "google.fr", type: "simple", isRegex: false },
    ],
  },

  // ───── REGIONAL: EASTASIA.CHINA ─────

  {
    id: "template-eastasia-china-ai",
    category: "ai",
    region: "eastasia.china",
    groupName: "🇨🇳 AI",
    icon: Robot,
    groupColor: "cyan",
    strict: false,
    merge: false,
    patterns: [
      { value: "doubao.com", type: "simple", isRegex: false },
      { value: "deepseek.com", type: "simple", isRegex: false },
      { value: "yiyan.baidu.com", type: "simple", isRegex: false },
      { value: "tongyi.aliyun.com", type: "simple", isRegex: false },
      { value: "hunyuan.tencent.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-china-cloud",
    category: "cloud",
    region: "eastasia.china",
    groupName: "🇨🇳 Cloud",
    icon: CloudArrowUp,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "aliyun.com", type: "simple", isRegex: false },
      { value: "cloud.tencent.com", type: "simple", isRegex: false },
      { value: "huaweicloud.com", type: "simple", isRegex: false },
      { value: "baidubce.com", type: "simple", isRegex: false },
      { value: "volcengine.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-china-finance",
    category: "finance",
    region: "eastasia.china",
    groupName: "🇨🇳 Finance",
    icon: Bank,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "alipay.com", type: "simple", isRegex: false },
      { value: "pay.weixin.qq.com", type: "simple", isRegex: false },
      { value: "eastmoney.com", type: "simple", isRegex: false },
      { value: "10jqka.com.cn", type: "simple", isRegex: false },
      { value: "wallstreetcn.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-china-gaming",
    category: "gaming",
    region: "eastasia.china",
    groupName: "🇨🇳 Gaming",
    icon: GameController,
    groupColor: "purple",
    strict: false,
    merge: false,
    patterns: [
      { value: "taptap.com", type: "simple", isRegex: false },
      { value: "game.gtimg.com", type: "simple", isRegex: false },
      { value: "gamersky.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-china-jobs",
    category: "jobs",
    region: "eastasia.china",
    groupName: "🇨🇳 Jobs",
    icon: Suitcase,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "51job.com", type: "simple", isRegex: false },
      { value: "zhaopin.com", type: "simple", isRegex: false },
      { value: "liepin.com", type: "simple", isRegex: false },
      { value: "lagou.com", type: "simple", isRegex: false },
      { value: "bosszhipin.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-china-messaging",
    category: "messaging",
    region: "eastasia.china",
    groupName: "🇨🇳 Messaging",
    icon: Chats,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "wechat.com", type: "simple", isRegex: false },
      { value: "qq.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-china-music",
    category: "music",
    region: "eastasia.china",
    groupName: "🇨🇳 Music",
    icon: MusicNotes,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "music.163.com", type: "simple", isRegex: false },
      { value: "y.qq.com", type: "simple", isRegex: false },
      { value: "kugou.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-china-news",
    category: "news",
    region: "eastasia.china",
    groupName: "🇨🇳 News",
    icon: Newspaper,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "toutiao.com", type: "simple", isRegex: false },
      { value: "news.baidu.com", type: "simple", isRegex: false },
      { value: "sina.com.cn", type: "simple", isRegex: false },
      { value: "qq.com", type: "simple", isRegex: false },
      { value: "sohu.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-china-shopping",
    category: "shopping",
    region: "eastasia.china",
    groupName: "🇨🇳 Shopping",
    icon: ShoppingCart,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "taobao.com", type: "simple", isRegex: false },
      { value: "jd.com", type: "simple", isRegex: false },
      { value: "tmall.com", type: "simple", isRegex: false },
      { value: "pinduoduo.com", type: "simple", isRegex: false },
      { value: "vip.com", type: "simple", isRegex: false },
      { value: "1688.com", type: "simple", isRegex: false },
      { value: "dewu.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-china-social",
    category: "social",
    region: "eastasia.china",
    groupName: "🇨🇳 Social",
    icon: Users,
    groupColor: "pink",
    strict: false,
    merge: false,
    patterns: [
      { value: "weibo.com", type: "simple", isRegex: false },
      { value: "xiaohongshu.com", type: "simple", isRegex: false },
      { value: "douban.com", type: "simple", isRegex: false },
      { value: "tieba.baidu.com", type: "simple", isRegex: false },
      { value: "weixin.qq.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-china-video",
    category: "video",
    region: "eastasia.china",
    groupName: "🇨🇳 Video",
    icon: Video,
    groupColor: "red",
    strict: false,
    merge: false,
    patterns: [
      { value: "bilibili.com", type: "simple", isRegex: false },
      { value: "douyin.com", type: "simple", isRegex: false },
      { value: "iqiyi.com", type: "simple", isRegex: false },
      { value: "v.qq.com", type: "simple", isRegex: false },
      { value: "youku.com", type: "simple", isRegex: false },
      { value: "kuaishou.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-china-work",
    category: "work",
    region: "eastasia.china",
    groupName: "🇨🇳 Work",
    icon: Briefcase,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "dingtalk.com", type: "simple", isRegex: false },
      { value: "feishu.cn", type: "simple", isRegex: false },
      { value: "wecom.com", type: "simple", isRegex: false },
      { value: "maimai.cn", type: "simple", isRegex: false },
    ],
  },

  // ───── REGIONAL: EASTASIA.KOREA ─────

  {
    id: "template-eastasia-korea-finance",
    category: "finance",
    region: "eastasia.korea",
    groupName: "🇰🇷 Finance",
    icon: Bank,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "kakaobank.com", type: "simple", isRegex: false },
      { value: "toss.im", type: "simple", isRegex: false },
      { value: "naverpay.com", type: "simple", isRegex: false },
      { value: "dhlottery.co.kr", type: "simple", isRegex: false },
      { value: "upbit.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-korea-forums",
    category: "forums",
    region: "eastasia.korea",
    groupName: "🇰🇷 Forums",
    icon: ChatCircleDots,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "dcinside.com", type: "simple", isRegex: false },
      { value: "fmkorea.com", type: "simple", isRegex: false },
      { value: "arca.live", type: "simple", isRegex: false },
      { value: "theqoo.net", type: "simple", isRegex: false },
      { value: "clien.net", type: "simple", isRegex: false },
      { value: "ppomppu.co.kr", type: "simple", isRegex: false },
      { value: "ruliweb.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-korea-gaming",
    category: "gaming",
    region: "eastasia.korea",
    groupName: "🇰🇷 Gaming",
    icon: GameController,
    groupColor: "purple",
    strict: false,
    merge: false,
    patterns: [
      { value: "nexon.com", type: "simple", isRegex: false },
      { value: "inven.co.kr", type: "simple", isRegex: false },
      { value: "ruliweb.com", type: "simple", isRegex: false },
      { value: "netmarble.com", type: "simple", isRegex: false },
      { value: "sooplive.co.kr", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-korea-jobs",
    category: "jobs",
    region: "eastasia.korea",
    groupName: "🇰🇷 Jobs",
    icon: Suitcase,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "saramin.co.kr", type: "simple", isRegex: false },
      { value: "jobkorea.co.kr", type: "simple", isRegex: false },
      { value: "wanted.co.kr", type: "simple", isRegex: false },
      { value: "rocketpunch.com", type: "simple", isRegex: false },
      { value: "peoplenjob.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-korea-messaging",
    category: "messaging",
    region: "eastasia.korea",
    groupName: "🇰🇷 Messaging",
    icon: Chats,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "kakao.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-korea-news",
    category: "news",
    region: "eastasia.korea",
    groupName: "🇰🇷 News",
    icon: Newspaper,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "naver.com", type: "simple", isRegex: false },
      { value: "daum.net", type: "simple", isRegex: false },
      { value: "nate.com", type: "simple", isRegex: false },
      { value: "chosun.com", type: "simple", isRegex: false },
      { value: "donga.com", type: "simple", isRegex: false },
      { value: "hankyung.com", type: "simple", isRegex: false },
      { value: "news.naver.com", type: "simple", isRegex: false },
      { value: "joongang.co.kr", type: "simple", isRegex: false },
      { value: "hani.co.kr", type: "simple", isRegex: false },
      { value: "yna.co.kr", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-korea-reading",
    category: "reading",
    region: "eastasia.korea",
    groupName: "🇰🇷 Reading",
    icon: Bookmarks,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "namu.wiki", type: "simple", isRegex: false },
      { value: "tistory.com", type: "simple", isRegex: false },
      { value: "newtoki469.com", type: "simple", isRegex: false },
      { value: "manatoki469.net", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-korea-shopping",
    category: "shopping",
    region: "eastasia.korea",
    groupName: "🇰🇷 Shopping",
    icon: ShoppingCart,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "coupang.com", type: "simple", isRegex: false },
      { value: "gmarket.co.kr", type: "simple", isRegex: false },
      { value: "ssg.com", type: "simple", isRegex: false },
      { value: "11st.co.kr", type: "simple", isRegex: false },
      { value: "kurly.com", type: "simple", isRegex: false },
      { value: "lotteon.com", type: "simple", isRegex: false },
      { value: "shopping.naver.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-korea-social",
    category: "social",
    region: "eastasia.korea",
    groupName: "🇰🇷 Social",
    icon: Users,
    groupColor: "pink",
    strict: false,
    merge: false,
    patterns: [
      { value: "naver.com", type: "simple", isRegex: false },
      { value: "kakaocorp.com", type: "simple", isRegex: false },
      { value: "line.me", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-korea-google",
    category: "google",
    region: "eastasia.korea",
    groupName: "🇰🇷 Google",
    icon: Globe,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "google.co.kr", type: "simple", isRegex: false },
    ],
  },

  // ───── REGIONAL: EASTASIA.JAPAN ─────

  {
    id: "template-eastasia-japan-finance",
    category: "finance",
    region: "eastasia.japan",
    groupName: "🇯🇵 Finance",
    icon: Bank,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "rakuten-sec.co.jp", type: "simple", isRegex: false },
      { value: "finance.yahoo.co.jp", type: "simple", isRegex: false },
      { value: "mufg.jp", type: "simple", isRegex: false },
      { value: "smbc.co.jp", type: "simple", isRegex: false },
      { value: "mizuhobank.co.jp", type: "simple", isRegex: false },
      { value: "sbisec.co.jp", type: "simple", isRegex: false },
      { value: "minkabu.jp", type: "simple", isRegex: false },
      { value: "kabutan.jp", type: "simple", isRegex: false },
      { value: "rakuten-bank.co.jp", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-japan-food",
    category: "food",
    region: "eastasia.japan",
    groupName: "🇯🇵 Food",
    icon: ForkKnife,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "tabelog.com", type: "simple", isRegex: false },
      { value: "hotpepper.jp", type: "simple", isRegex: false },
      { value: "cookpad.com", type: "simple", isRegex: false },
      { value: "gnavi.co.jp", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-japan-forums",
    category: "forums",
    region: "eastasia.japan",
    groupName: "🇯🇵 Forums",
    icon: ChatCircleDots,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "5ch.net", type: "simple", isRegex: false },
      { value: "bakusai.com", type: "simple", isRegex: false },
      { value: "girlschannel.net", type: "simple", isRegex: false },
      { value: "pixiv.net", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-japan-gaming",
    category: "gaming",
    region: "eastasia.japan",
    groupName: "🇯🇵 Gaming",
    icon: GameController,
    groupColor: "purple",
    strict: false,
    merge: false,
    patterns: [
      { value: "gamewith.jp", type: "simple", isRegex: false },
      { value: "game8.jp", type: "simple", isRegex: false },
      { value: "dmm.com", type: "simple", isRegex: false },
      { value: "famitsu.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-japan-messaging",
    category: "messaging",
    region: "eastasia.japan",
    groupName: "🇯🇵 Messaging",
    icon: Chats,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "line.me", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-japan-news",
    category: "news",
    region: "eastasia.japan",
    groupName: "🇯🇵 News",
    icon: Newspaper,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "yahoo.co.jp", type: "simple", isRegex: false },
      { value: "nikkei.com", type: "simple", isRegex: false },
      { value: "asahi.com", type: "simple", isRegex: false },
      { value: "yomiuri.co.jp", type: "simple", isRegex: false },
      { value: "mainichi.jp", type: "simple", isRegex: false },
      { value: "news.yahoo.co.jp", type: "simple", isRegex: false },
      { value: "auone.jp", type: "simple", isRegex: false },
      { value: "livedoor.jp", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-japan-reading",
    category: "reading",
    region: "eastasia.japan",
    groupName: "🇯🇵 Reading",
    icon: Bookmarks,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "pixiv.net", type: "simple", isRegex: false },
      { value: "note.com", type: "simple", isRegex: false },
      { value: "syosetu.com", type: "simple", isRegex: false },
      { value: "cmoa.jp", type: "simple", isRegex: false },
      { value: "ameblo.jp", type: "simple", isRegex: false },
      { value: "livedoor.jp", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-japan-shopping",
    category: "shopping",
    region: "eastasia.japan",
    groupName: "🇯🇵 Shopping",
    icon: ShoppingCart,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "rakuten.co.jp", type: "simple", isRegex: false },
      { value: "amazon.co.jp", type: "simple", isRegex: false },
      { value: "mercari.com", type: "simple", isRegex: false },
      { value: "shopping.yahoo.co.jp", type: "simple", isRegex: false },
      { value: "kakaku.com", type: "simple", isRegex: false },
      { value: "zozo.jp", type: "simple", isRegex: false },
      { value: "yodobashi.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-japan-social",
    category: "social",
    region: "eastasia.japan",
    groupName: "🇯🇵 Social",
    icon: Users,
    groupColor: "pink",
    strict: false,
    merge: false,
    patterns: [
      { value: "ameblo.jp", type: "simple", isRegex: false },
      { value: "nicovideo.jp", type: "simple", isRegex: false },
      { value: "line.me", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-japan-travel",
    category: "travel",
    region: "eastasia.japan",
    groupName: "🇯🇵 Travel",
    icon: AirplaneTilt,
    groupColor: "cyan",
    strict: false,
    merge: false,
    patterns: [
      { value: "jreast.co.jp", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-eastasia-japan-google",
    category: "google",
    region: "eastasia.japan",
    groupName: "🇯🇵 Google",
    icon: Globe,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "google.co.jp", type: "simple", isRegex: false },
    ],
  },

  // ───── REGIONAL: SOUTHASIA.INDIA ─────

  {
    id: "template-southasia-india-education",
    category: "education",
    region: "southasia.india",
    groupName: "🇮🇳 Education",
    icon: GraduationCap,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "byjus.com", type: "simple", isRegex: false },
      { value: "unacademy.com", type: "simple", isRegex: false },
      { value: "upgrad.com", type: "simple", isRegex: false },
      { value: "physicswallah.live", type: "simple", isRegex: false },
      { value: "pw.live", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-southasia-india-finance",
    category: "finance",
    region: "southasia.india",
    groupName: "🇮🇳 Finance",
    icon: Bank,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "hdfcbank.com", type: "simple", isRegex: false },
      { value: "onlinesbi.sbi", type: "simple", isRegex: false },
      { value: "icicibank.com", type: "simple", isRegex: false },
      { value: "paytm.com", type: "simple", isRegex: false },
      { value: "phonepe.com", type: "simple", isRegex: false },
      { value: "moneycontrol.com", type: "simple", isRegex: false },
      { value: "zerodha.com", type: "simple", isRegex: false },
      { value: "goodreturns.in", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-southasia-india-food",
    category: "food",
    region: "southasia.india",
    groupName: "🇮🇳 Food",
    icon: ForkKnife,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "zomato.com", type: "simple", isRegex: false },
      { value: "swiggy.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-southasia-india-jobs",
    category: "jobs",
    region: "southasia.india",
    groupName: "🇮🇳 Jobs",
    icon: Suitcase,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "naukri.com", type: "simple", isRegex: false },
      { value: "foundit.in", type: "simple", isRegex: false },
      { value: "apna.co", type: "simple", isRegex: false },
      { value: "shine.com", type: "simple", isRegex: false },
      { value: "internshala.com", type: "simple", isRegex: false },
      { value: "workindia.in", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-southasia-india-news",
    category: "news",
    region: "southasia.india",
    groupName: "🇮🇳 News",
    icon: Newspaper,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "ndtv.com", type: "simple", isRegex: false },
      { value: "timesofindia.indiatimes.com", type: "simple", isRegex: false },
      { value: "hindustantimes.com", type: "simple", isRegex: false },
      { value: "indianexpress.com", type: "simple", isRegex: false },
      { value: "aajtak.in", type: "simple", isRegex: false },
      { value: "indiatimes.com", type: "simple", isRegex: false },
      { value: "news18.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-southasia-india-shopping",
    category: "shopping",
    region: "southasia.india",
    groupName: "🇮🇳 Shopping",
    icon: ShoppingCart,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "flipkart.com", type: "simple", isRegex: false },
      { value: "amazon.in", type: "simple", isRegex: false },
      { value: "myntra.com", type: "simple", isRegex: false },
      { value: "meesho.com", type: "simple", isRegex: false },
      { value: "ajio.com", type: "simple", isRegex: false },
      { value: "nykaa.com", type: "simple", isRegex: false },
      { value: "jiomart.com", type: "simple", isRegex: false },
      { value: "snapdeal.com", type: "simple", isRegex: false },
      { value: "shopclues.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-southasia-india-travel",
    category: "travel",
    region: "southasia.india",
    groupName: "🇮🇳 Travel",
    icon: AirplaneTilt,
    groupColor: "cyan",
    strict: false,
    merge: false,
    patterns: [
      { value: "makemytrip.com", type: "simple", isRegex: false },
      { value: "goibibo.com", type: "simple", isRegex: false },
      { value: "cleartrip.com", type: "simple", isRegex: false },
      { value: "irctc.co.in", type: "simple", isRegex: false },
      { value: "yatra.com", type: "simple", isRegex: false },
      { value: "ixigo.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-southasia-india-video",
    category: "video",
    region: "southasia.india",
    groupName: "🇮🇳 Video",
    icon: Video,
    groupColor: "red",
    strict: false,
    merge: false,
    patterns: [
      { value: "hotstar.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-southasia-india-google",
    category: "google",
    region: "southasia.india",
    groupName: "🇮🇳 Google",
    icon: Globe,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "google.co.in", type: "simple", isRegex: false },
    ],
  },

  // ───── REGIONAL: LATAM ─────

  {
    id: "template-latam-education",
    category: "education",
    region: "latam",
    groupName: "🌎 Education",
    icon: GraduationCap,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "uol.com.br/educacao", type: "simple", isRegex: false },
      { value: "estacio.br", type: "simple", isRegex: false },
      { value: "unip.br", type: "simple", isRegex: false },
      { value: "tec.mx", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-latam-finance",
    category: "finance",
    region: "latam",
    groupName: "🌎 Finance",
    icon: Bank,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "nubank.com.br", type: "simple", isRegex: false },
      { value: "mercadopago.com", type: "simple", isRegex: false },
      { value: "itau.com.br", type: "simple", isRegex: false },
      { value: "caixa.gov.br", type: "simple", isRegex: false },
      { value: "santander.com.br", type: "simple", isRegex: false },
      { value: "bb.com.br", type: "simple", isRegex: false },
      { value: "bradesco.com.br", type: "simple", isRegex: false },
    ],
  },
  // {
  //   id: "template-latam-jobs",
  //   category: "jobs",
  //   region: "latam",
  //   groupName: "🌎 Jobs",
  //   icon: Suitcase,
  //   groupColor: "blue",
  //   strict: false,
  //   merge: false,
  //   patterns: [
  //     { value: "vagas.com.br", type: "simple", isRegex: false },
  //     { value: "computrabajo.com", type: "simple", isRegex: false },
  //   ],
  // },
  {
    id: "template-latam-news",
    category: "news",
    region: "latam",
    groupName: "🌎 News",
    icon: Newspaper,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "globo.com", type: "simple", isRegex: false },
      { value: "eluniversal.com.mx", type: "simple", isRegex: false },
      { value: "infobae.com", type: "simple", isRegex: false },
      { value: "clarin.com", type: "simple", isRegex: false },
      { value: "folha.uol.com.br", type: "simple", isRegex: false },
      { value: "g1.globo.com", type: "simple", isRegex: false },
      { value: "uol.com.br", type: "simple", isRegex: false },
      { value: "canalrcn.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-latam-shopping",
    category: "shopping",
    region: "latam",
    groupName: "🌎 Shopping",
    icon: ShoppingCart,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "mercadolibre.com", type: "simple", isRegex: false },
      { value: "amazon.com.br", type: "simple", isRegex: false },
      { value: "amazon.com.mx", type: "simple", isRegex: false },
      { value: "magazineluiza.com.br", type: "simple", isRegex: false },
      { value: "coppel.com", type: "simple", isRegex: false },
      { value: "americanas.com.br", type: "simple", isRegex: false },
      { value: "casasbahia.com.br", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-latam-travel",
    category: "travel",
    region: "latam",
    groupName: "🌎 Travel",
    icon: AirplaneTilt,
    groupColor: "cyan",
    strict: false,
    merge: false,
    patterns: [
      { value: "despegar.com", type: "simple", isRegex: false },
      { value: "decolar.com", type: "simple", isRegex: false },
      { value: "cvc.com.br", type: "simple", isRegex: false },
      { value: "latamairlines.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-latam-google",
    category: "google",
    region: "latam",
    groupName: "🌎 Google",
    icon: Globe,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "google.com.br", type: "simple", isRegex: false },
      { value: "google.com.mx", type: "simple", isRegex: false },
      { value: "google.com.ar", type: "simple", isRegex: false },
      { value: "google.com.co", type: "simple", isRegex: false },
      { value: "google.cl", type: "simple", isRegex: false },
      { value: "google.com.pe", type: "simple", isRegex: false },
    ],
  },

  // ───── REGIONAL: MENA.GULF ─────

  {
    id: "template-mena-gulf-finance",
    category: "finance",
    region: "mena.gulf",
    groupName: "🌍 Finance",
    icon: Bank,
    groupColor: "green",
    strict: false,
    merge: false,
    patterns: [
      { value: "emiratesnbd.com", type: "simple", isRegex: false },
      { value: "adcb.com", type: "simple", isRegex: false },
      { value: "bankfab.com", type: "simple", isRegex: false },
      { value: "alrajhibank.com.sa", type: "simple", isRegex: false },
      { value: "stcpay.com.sa", type: "simple", isRegex: false },
      { value: "mashreq.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-mena-gulf-food",
    category: "food",
    region: "mena.gulf",
    groupName: "🌍 Food",
    icon: ForkKnife,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "talabat.com", type: "simple", isRegex: false },
      { value: "hungerstation.com", type: "simple", isRegex: false },
      { value: "jahez.net", type: "simple", isRegex: false },
      { value: "instashop.com", type: "simple", isRegex: false },
      { value: "deliveroo.ae", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-mena-gulf-health",
    category: "health",
    region: "mena.gulf",
    groupName: "🌍 Health",
    icon: Heartbeat,
    groupColor: "red",
    strict: false,
    merge: false,
    patterns: [
      { value: "nahdionline.com", type: "simple", isRegex: false },
      { value: "webteb.com", type: "simple", isRegex: false },
      { value: "nmc.ae", type: "simple", isRegex: false },
      { value: "dha.gov.ae", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-mena-gulf-news",
    category: "news",
    region: "mena.gulf",
    groupName: "🌍 News",
    icon: Newspaper,
    groupColor: "yellow",
    strict: false,
    merge: false,
    patterns: [
      { value: "khaleejtimes.com", type: "simple", isRegex: false },
      { value: "gulfnews.com", type: "simple", isRegex: false },
      { value: "aljazeera.net", type: "simple", isRegex: false },
      { value: "sabq.org", type: "simple", isRegex: false },
      { value: "alarabiya.net", type: "simple", isRegex: false },
      { value: "okaz.com.sa", type: "simple", isRegex: false },
      { value: "asharq.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-mena-gulf-shopping",
    category: "shopping",
    region: "mena.gulf",
    groupName: "🌍 Shopping",
    icon: ShoppingCart,
    groupColor: "orange",
    strict: false,
    merge: false,
    patterns: [
      { value: "noon.com", type: "simple", isRegex: false },
      { value: "amazon.ae", type: "simple", isRegex: false },
      { value: "amazon.sa", type: "simple", isRegex: false },
      { value: "namshi.com", type: "simple", isRegex: false },
      { value: "dubizzle.com", type: "simple", isRegex: false },
      { value: "haraj.com.sa", type: "simple", isRegex: false },
      { value: "jarir.com", type: "simple", isRegex: false },
      { value: "extra.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-mena-gulf-travel",
    category: "travel",
    region: "mena.gulf",
    groupName: "🌍 Travel",
    icon: AirplaneTilt,
    groupColor: "cyan",
    strict: false,
    merge: false,
    patterns: [
      { value: "emirates.com", type: "simple", isRegex: false },
      { value: "airarabia.com", type: "simple", isRegex: false },
      { value: "qatarairways.com", type: "simple", isRegex: false },
      { value: "saudia.com", type: "simple", isRegex: false },
      { value: "almosafer.com", type: "simple", isRegex: false },
      { value: "visitsaudi.com", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-mena-gulf-work",
    category: "work",
    region: "mena.gulf",
    groupName: "🌍 Work",
    icon: Briefcase,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "uaepass.ae", type: "simple", isRegex: false },
      { value: "absher.sa", type: "simple", isRegex: false },
      { value: "mol.gov.ae", type: "simple", isRegex: false },
      { value: "mohap.gov.ae", type: "simple", isRegex: false },
    ],
  },
  {
    id: "template-mena-gulf-google",
    category: "google",
    region: "mena.gulf",
    groupName: "🌍 Google",
    icon: Globe,
    groupColor: "blue",
    strict: false,
    merge: false,
    patterns: [
      { value: "google.ae", type: "simple", isRegex: false },
      { value: "google.com.sa", type: "simple", isRegex: false },
      { value: "google.com.eg", type: "simple", isRegex: false },
      { value: "google.com.kw", type: "simple", isRegex: false },
      { value: "google.com.qa", type: "simple", isRegex: false },
      { value: "google.com.bh", type: "simple", isRegex: false },
    ],
  },
];

// ─────────────────────────────────────────────
// Build select options with human-readable subtitles
// ─────────────────────────────────────────────

const DOMAIN_DISPLAY_OVERRIDES = {
  'nytimes': 'NYTimes',
  'bbc': 'BBC',
  'cnn': 'CNN',
  'youtube': 'YouTube',
  'github': 'GitHub',
  'x': 'X',
  'espn': 'ESPN',
  'nba': 'NBA',
  'nfl': 'NFL',
  'mlb': 'MLB',
  'ign': 'IGN',
  'nih': 'NIH',
  'jd': 'JD',
  'bmo': 'BMO',
  'cibc': 'CIBC',
  'td': 'TD',
  'qq': 'QQ',
  'v': 'Tencent',
  'y': 'QQ Music',
  'docs': 'Google Docs',
  'sheets': 'Google Sheets',
  'slides': 'Google Slides',
  'drive': 'Google Drive',
  'news': 'Google News',
  'music': 'Apple Music',
  'web': 'WhatsApp',
  'store': 'Steam',
  'teams': 'MS Teams',
  'onedrive': 'OneDrive',
  'tieba': 'Tieba',
  'gemini': 'Gemini',
  'mail': 'Gmail',
  'maps': 'Google Maps',
  'calendar': 'Google Calendar',
  'photos': 'Google Photos',
  'meet': 'Google Meet',
  'translate': 'Google Translate',
  'play': 'Google Play',
  'classroom': 'Google Classroom',
  'earth': 'Google Earth',
  'keep': 'Google Keep',
  'one': 'Google One',
  'voice': 'Google Voice',
  'contacts': 'Google Contacts',
  'accounts': 'Google Accounts',
  'google': 'Google Search',
};

function formatDomainName(val) {
  // Strip "www." and grab the first subdomain/name segment
  const cleaned = val.replace(/^www\./, '');
  const firstPart = cleaned.split('.')[0];

  if (DOMAIN_DISPLAY_OVERRIDES[firstPart]) {
    return DOMAIN_DISPLAY_OVERRIDES[firstPart];
  }

  // Capitalize first letter
  return firstPart.charAt(0).toUpperCase() + firstPart.slice(1);
}

export const TEMPLATE_OPTIONS = PRESET_TEMPLATES.map((t) => {
  const formattedNames = t.patterns.slice(0, 4).map(p => formatDomainName(p.value));
  const subtitle = formattedNames.join(', ') + (t.patterns.length > 4 ? ', etc.' : '');
  const regionMeta = getRegionMeta(t.region);

  return {
    value: t.id,
    label: t.groupName,
    icon: t.icon,
    region: t.region,
    category: t.category,
    subtitle,
    // Searchable text: title + category + region title + all domain names
    searchText: `${t.groupName} ${t.category ?? ''} ${regionMeta.title} ${regionMeta.label} ${t.patterns.map(p => p.value).join(' ')}`,
  };
});

