import React, { useState, useEffect } from 'react';
import { ArrowLeft, ArrowRight, ArrowUp, ArrowDown } from '@phosphor-icons/react';
import { MagicDotStep } from './types';

export const DEV_REPLAY_TUTORIALS = false;

export const TUTORIAL_DATA = {
  'main-overlay': {
    key: 'main_tutorial_done',
    sequence: [
      {
        target: 'header',
        position: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 16,
        tooltip: "Welcome in! Let's get you settled.",
        tooltipPosition: 'right',
      },
      {
        target: 'triage',
        position: 'left',
        tooltipPosition: 'left',
        duration: 4500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 16,
        tooltip: (
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
            Use <ArrowLeft size={13} weight="bold" /> <ArrowRight size={13} weight="bold" /> to
            triage tabs
          </span>
        ),
      },
      {
        target: 'swipe',
        position: 'left',
        tooltipPosition: 'left',
        duration: 1900,
        color: 'var(--magic-dot)',
        pulse: false,
        size: 16,
        tooltip: 'or click and drag the cards!',
      },
      {
        target: 'bookmark',
        position: 'left',
        tooltipPosition: 'left',
        duration: 1800,
        color: 'var(--magic-dot)',
        pulse: false,
        size: 16,
        tooltip: (
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
            Press <ArrowUp size={13} weight="bold" /> to Bookmark
          </span>
        ),
      },
      {
        target: 'group',
        position: 'left',
        tooltipPosition: 'left',
        duration: 1700,
        color: 'var(--magic-dot)',
        pulse: false,
        size: 16,
        tooltip: (
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
            or <ArrowDown size={13} weight="bold" /> to move to a tab group.
          </span>
        ),
      },
      {
        target: 'bookmark',
        position: 'left',
        tooltipPosition: 'left',
        duration: 1800,
        color: 'var(--magic-dot)',
        pulse: false,
        size: 16,
        tooltip: 'For Bookmarks and Tab Groups...',
      },
      {
        target: 'navigate',
        position: 'left',
        tooltipPosition: 'left',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 16,
        tooltip: (
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
            move through the list with <ArrowUp size={13} weight="bold" />{' '}
            <ArrowDown size={13} weight="bold" />
          </span>
        ),
      },
      {
        target: 'search',
        position: 'left',
        tooltipPosition: 'left',
        duration: 1900,
        color: 'var(--magic-dot)',
        pulse: false,
        size: 16,
        tooltip: 'start typing to search,',
      },
      {
        target: 'confirm',
        position: 'left',
        tooltipPosition: 'left',
        duration: 1800,
        color: 'var(--magic-dot)',
        pulse: false,
        size: 16,
        tooltip: 'and press Enter to confirm and continue.',
      },
      {
        target: 'go',
        position: 'right',
        tooltipPosition: 'right',
        duration: 3000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 16,
        tooltip: 'Now! Go close your tabs!',
      },
    ],
  },
  'auto-close': {
    key: 'autoclose_tutorial_done',
    sequence: [
      {
        target: 'ac-header',
        position: 'right',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip:
          "Welcome to the Auto Close wizard! Let's set up some rules to sweep away old, stale tabs.",
      },
      {
        target: 'ac-toggle',
        position: 'bottom',
        tooltipPosition: 'left',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip:
          'Flip this switch to turn on the magic and automatically close old tabs in the background.',
      },
      {
        target: 'ac-threshold',
        position: 'left',
        tooltipPosition: 'left',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: 'Just tell us how old a tab needs to be before it gets the boot.',
      },
      {
        target: 'ac-grid',
        position: 'left',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip:
          'Any tabs that already qualify will show up right here, ready for the chopping block.',
      },
      {
        target: 'ac-graveyard',
        position: 'left',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip:
          "If the auto-closer runs in the background, it'll save the tabs it closed right here, so you can check or restore them anytime.",
      },
      {
        target: 'ac-save',
        position: 'left',
        tooltipPosition: 'left',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: "Hit save and it'll sweep them away quietly in the background for you!",
      },
    ],
  },
  'close-old': {
    key: 'closeold_tutorial_done',
    sequence: [
      {
        target: 'ac-header',
        position: 'right',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: "Welcome to Close Old Tabs! Let's sweep away those stale tabs in one go.",
      },
      {
        target: 'ac-threshold',
        position: 'bottom',
        tooltipPosition: 'left',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: 'Just tell us how old a tab needs to be before it gets the boot.',
      },
      {
        target: 'ac-grid',
        position: 'left',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip:
          'These tabs are on the chopping block. Click any you want to save from being closed!',
      },
      {
        target: 'ac-toggle-all',
        position: 'left',
        tooltipPosition: 'left',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: 'Too many to click? Toggle them all in one go right here.',
      },
      {
        target: 'ac-confirm',
        position: 'left',
        tooltipPosition: 'left',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip: "When you're ready, hit this button to close them all!",
      },
    ],
  },
  'auto-sorter': {
    key: 'autosorter_tutorial_done',
    sequence: [
      {
        target: 'as-header',
        position: 'right',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip:
          "Welcome to the Auto Sorter wizard! Let's set up some rules to keep your tabs perfectly organized.",
      },
      {
        target: 'as-toggle',
        position: 'bottom',
        tooltipPosition: 'left',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: 'Flip this switch to turn on the magic and automatically sort any new tabs.',
      },
      {
        target: 'as-sortby',
        position: 'left',
        tooltipPosition: 'left',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: 'You can choose to sort everything neatly by URL, or by page title.',
      },
      {
        target: 'as-preview',
        position: 'left',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip: 'Take a peek! This is exactly how your tabs will look after they get sorted.',
      },
      {
        target: 'as-sortnow',
        position: 'left',
        tooltipPosition: 'right',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: 'Just want a quick cleanup? You can run a one-time sort right here.',
      },
      {
        target: 'as-save',
        position: 'left',
        tooltipPosition: 'left',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: 'Hit save to let it run quietly in the background for you!',
      },
    ],
  },
  'auto-smusher': {
    key: 'autosmusher_tutorial_done',
    sequence: [
      {
        target: 'sm-header',
        position: 'right',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip:
          "Welcome to the Auto Smusher wizard! Let's set up some rules to crush pesky duplicate tabs.",
      },
      {
        target: 'sm-toggle',
        position: 'bottom',
        tooltipPosition: 'left',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: 'Just flip this on, kick back, and forget duplicates ever existed.',
      },
      {
        target: 'sm-settings',
        position: 'left',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip:
          "Want to be specific? You can fine-tune exactly what counts as a 'duplicate' here.",
      },
      {
        target: 'sm-preview',
        position: 'left',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip: 'Any duplicates you already have open will pop up right here.',
      },
      {
        target: 'sm-save',
        position: 'left',
        tooltipPosition: 'left',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: 'Smush that save button and let it do all the heavy lifting!',
      },
    ],
  },
  'auto-grouper': {
    key: 'autogrouper_tutorial_done',
    sequence: [
      {
        target: 'ag-header',
        position: 'right',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip:
          "Welcome to the Tab Grouper wizard! Let's set up some automated rules to keep your tabs grouped properly.",
      },
      {
        target: 'ag-toggle',
        position: 'bottom',
        tooltipPosition: 'left',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip: "Turn this on and it'll group your tabs for you as you browse.",
      },
      {
        target: 'ag-add-rule',
        position: 'bottom',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: 'Build your own rule — domain, URL pattern, regex, or rough match. ...',
      },
      {
        target: 'ag-templates',
        position: 'bottom',
        tooltipPosition: 'left',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: 'Templates are super useful! One click, pre-filled with popular sites.',
      },
      {
        target: 'ag-preview',
        position: 'left',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip: 'Watch the magic happen! Matching tabs will show up right here in real time.',
      },
      {
        target: 'ag-save',
        position: 'left',
        tooltipPosition: 'left',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: 'Save your rules and let it run quietly in the background!',
      },
    ],
  },
  bookmarks: {
    key: 'bookmarkmanager_tutorial_done',
    sequence: [
      {
        target: 'bm-header',
        position: 'right',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip: "Welcome to the Bookmark Manager wizard! Let's get your saved pages organized.",
      },
      {
        target: 'bm-grid-title',
        position: 'right',
        tooltipPosition: 'right',
        duration: 3000,
        color: 'var(--magic-dot)',
        pulse: true,
        dimBackground: true,
        size: 14,
        tooltip:
          'Click any bookmark to select it — perfect for mass-clearing a whole folder at once. You can also drag and drop items to reorder them or move them between folders!',
      },
      {
        target: 'bm-remove',
        position: 'left',
        tooltipPosition: 'left',
        duration: 3500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip:
          "Hit Remove down here to clear your selections. Don't worry, nothing is actually deleted yet! All changes are safely staged until you confirm them.",
      },
      {
        target: 'bm-collapse-expand',
        position: 'bottom',
        tooltipPosition: 'left',
        duration: 3500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip:
          'Got a massive tree of folders? Use Collapse all and Expand all to quickly navigate your hierarchy.',
      },
      {
        target: 'bm-date-used',
        position: 'right',
        tooltipPosition: 'right',
        duration: 3500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip:
          "You can find all those bookmarks you've never used, or haven't clicked in forever right here.",
      },
      {
        target: 'bm-date-added',
        position: 'right',
        tooltipPosition: 'right',
        duration: 3500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip:
          'And you can find out how long ago they were added here. Great for clearing out old stuff!',
      },
    ],
  },
  'list-view': {
    key: 'listview_tutorial_done',
    sequence: [
      {
        target: 'lv-header',
        position: 'right',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip: "Welcome to List View! Let's get a handle on all your tabs at once.",
      },
      {
        target: 'lv-search',
        position: 'bottom',
        tooltipPosition: 'bottom',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip: 'Looking for a specific tab? Just search by title or URL right here.',
      },
      {
        target: 'lv-view-toggle',
        position: 'left',
        tooltipPosition: 'left',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip: 'You can toggle between chunky grid cards or a super compact list view.',
      },
      {
        target: 'lv-sidebar',
        position: 'right',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip: 'Need to focus? Use the sidebar to filter by a specific tab group or domain.',
      },
      {
        target: 'lv-grid',
        position: 'top',
        tooltipPosition: 'top',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip:
          'Select your tabs by clicking, Shift+clicking, or even clicking and dragging over them!',
      },
      {
        target: 'lv-footer',
        position: 'top',
        tooltipPosition: 'top',
        duration: 3000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip:
          "Once you've got them selected, you can bulk keep, close, bookmark, or group them down here!",
      },
    ],
  },
  wizard: {
    key: 'atg_tutorial_done',
    sequence: [
      {
        target: 'wiz-header',
        position: 'right',
        tooltipPosition: 'right',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip:
          "Welcome to the Tab Grouper wizard! We'll help you organize your open tabs into groups in a flash.",
      },
      {
        target: 'wiz-left',
        position: 'right',
        tooltipPosition: 'right',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip: 'Your proposed tab groups are lined up over here on the left...',
      },
      {
        target: 'wiz-toggle',
        position: 'right',
        tooltipPosition: 'right',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip:
          "...and if you don't want to group a specific domain, just toggle it off right here!",
      },
      {
        target: 'wiz-right',
        position: 'left',
        tooltipPosition: 'right',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip:
          'The actual tabs that belong to the selected group are listed over here on the right.',
      },
      {
        target: 'wiz-name',
        position: 'bottom',
        tooltipPosition: 'left',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip: 'Not a fan of the auto-generated name? Just click to rename the group!',
      },
      {
        target: 'wiz-drag',
        position: 'top',
        tooltipPosition: 'left',
        duration: 3000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip:
          'You can even drag and drop individual tabs between groups to get things just right.',
      },
      {
        target: 'wiz-confirm',
        position: 'left',
        tooltipPosition: 'left',
        duration: 2000,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        dimBackground: true,
        tooltip: 'When everything looks good, click here to magically create your groups!',
      },
    ],
  },
  'watch-later': {
    key: 'watchlater_tutorial_done',
    sequence: [
      {
        target: 'wl-header',
        position: 'right',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip:
          "Welcome to the Watch Later wizard! Let's save those YouTube videos to your playlist.",
      },
      {
        target: 'wl-grid',
        position: 'left',
        tooltipPosition: 'right',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: 'All your open YouTube tabs are lined up right here. Click any you want to skip!',
      },
      {
        target: 'wl-save',
        position: 'left',
        tooltipPosition: 'left',
        duration: 2500,
        color: 'var(--magic-dot)',
        pulse: true,
        size: 14,
        tooltip: 'Ready? Hit this button to add them all to your Watch Later playlist!',
      },
    ],
  },
};

export function useTutorialSequence(id: keyof typeof TUTORIAL_DATA) {
  const data = TUTORIAL_DATA[id];

  // If invalid ID provided, return safe defaults
  const [showTutorial] = useState<boolean>(() => {
    if (!data) return false;
    if (DEV_REPLAY_TUTORIALS) return true;
    return !localStorage.getItem(data.key);
  });

  useEffect(() => {
    if (showTutorial && data && !DEV_REPLAY_TUTORIALS) {
      localStorage.setItem(data.key, '1');
    }
  }, [showTutorial, data]);

  return {
    showTutorial,
    sequence: data ? (data.sequence as MagicDotStep[]) : [],
  };
}
